---
title: "Lab 14 Homework"
author: "Chris Abe "
date: "`r Sys.Date()`"
output:
  html_document: 
    theme: spacelab
    toc: yes
    toc_float: yes
    keep_md: yes
---

## Lab 14 Binder
If you want to return to the binder, find the [repository and instructions here](https://github.com/hehouts/lab14_binder)

## Instructions
Answer the following questions in RMarkdown. Please embed all of your code and push your final work to your repository. Be sure to add your name to the author header above.



## Questions

1. Look up 'Data Scientist' at https://www.bls.gov/. What degree is required for this career? Is it a growing occupation?  
# Bachelor's degree. It is a growing occupation (36% expected growth from 2021-31)


2. How would you describe your data science skills on a resume for a job application? Write a blurb that reflects the skills you have learned in this course. 
#Proficient in R. Can clean data, make plots, and make basic apps. 

3. What are your current career interests, and how could your R skills support that career path? (hint: this might be good content for your LinkedIn profile ;)
#Currently I am interested in going into reserach or into industry. I am specifically looking  at research that focuses on microbiology and food. My R skills could support this path by helping me interpret data that comes from resarch projects. 

4. What about this course has been the most difficult for you? What has been the most rewarding?
#The most difficult part of this course was probably the initial learning curve. Learning how to code really is like learning another language. At first, I didn't spend as much time as I should have in between labs practicing, so I always felt like I had to relearn stuff during the next lab. Nothing is more rewarding than seeing your code run and give you the proper result when you first run it. 


5. What do you wish you had known, or what skills do you wish you had, before taking this class.
#I wish I had known that I had to constantly practice so that I could retain all of the different tips that I learned better. 

6. If we had 1 more lab in this class, what would you have liked to learn more about?

#If there were one more lab I would want it to be about apps in more depth (I guess learn what other types of apps that we could make in shiny). There seems to be so many possibilities with apps and its really cool to be able to code something that people could in theory use. 

7. Now that you have (almost!) completed this course, do you plan to persue further data or computer science skills? What do you plan to do?

#I do plan to continue. I'm taking an intro to Python class next quarter and in the future I might take more data science or bioinformatic classes. 

8. How important was working with a partner to your success in this class? If this class were transitioned to an online format, how do you think that would affect your understanding?

#I didn't really work with a partner that often in the class. I will say that having someone to bounce off ideas during the midterms did help me learn a lot. I would have learned a lot less online. I would have gotten distracted a lot more and would have done a lot worse overall (probably would have procrastinated more too). 

9. Did you complete the class evaluation? Please complete the class evaluation using the link provided in the announcements. Your feedback is very important and we appreciate your time.

#I will complete them! 

## Push your final code to GitHub!
Please be sure that you check the `keep md` file in the knit preferences. 
